"""Add on delete cascade

Revision ID: 28a864db62b4
Revises: 0a09a85b4fde
Create Date: 2026-06-06 15:13:27.438304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a864db62b4'
down_revision: Union[str, Sequence[str], None] = '0a09a85b4fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notes_tags_tag_id_fkey'), 'notes_tags', type_='foreignkey')
    op.drop_constraint(op.f('notes_tags_note_id_fkey'), 'notes_tags', type_='foreignkey')
    op.create_foreign_key(None, 'notes_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notes_tags', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes_tags', type_='foreignkey')
    op.drop_constraint(None, 'notes_tags', type_='foreignkey')
    op.create_foreign_key(op.f('notes_tags_note_id_fkey'), 'notes_tags', 'notes', ['note_id'], ['id'])
    op.create_foreign_key(op.f('notes_tags_tag_id_fkey'), 'notes_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
