"""Add server_default to created_at

Revision ID: 0a09a85b4fde
Revises: dcbb7b122aa3
Create Date: 2026-06-04 22:46:31.806944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a09a85b4fde'
down_revision: Union[str, Sequence[str], None] = 'dcbb7b122aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
