// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddNoteNotesPostData, AddNoteNotesPostErrors, AddNoteNotesPostResponses, DeleteNoteNotesNoteIdDeleteData, DeleteNoteNotesNoteIdDeleteErrors, DeleteNoteNotesNoteIdDeleteResponses, EditNoteNotesNoteIdPutData, EditNoteNotesNoteIdPutErrors, EditNoteNotesNoteIdPutResponses, GetNotesNotesGetData, GetNotesNotesGetResponses, ViewNoteNotesNoteIdGetData, ViewNoteNotesNoteIdGetErrors, ViewNoteNotesNoteIdGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Notes
 */
export const getNotesNotesGet = <ThrowOnError extends boolean = false>(options?: Options<GetNotesNotesGetData, ThrowOnError>): RequestResult<GetNotesNotesGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetNotesNotesGetResponses, unknown, ThrowOnError>({ url: '/notes', ...options });

/**
 * Add Note
 */
export const addNoteNotesPost = <ThrowOnError extends boolean = false>(options: Options<AddNoteNotesPostData, ThrowOnError>): RequestResult<AddNoteNotesPostResponses, AddNoteNotesPostErrors, ThrowOnError> => (options.client ?? client).post<AddNoteNotesPostResponses, AddNoteNotesPostErrors, ThrowOnError>({
    url: '/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Note
 */
export const deleteNoteNotesNoteIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteNoteNotesNoteIdDeleteData, ThrowOnError>): RequestResult<DeleteNoteNotesNoteIdDeleteResponses, DeleteNoteNotesNoteIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteNoteNotesNoteIdDeleteResponses, DeleteNoteNotesNoteIdDeleteErrors, ThrowOnError>({ url: '/notes/{note_id}', ...options });

/**
 * View Note
 */
export const viewNoteNotesNoteIdGet = <ThrowOnError extends boolean = false>(options: Options<ViewNoteNotesNoteIdGetData, ThrowOnError>): RequestResult<ViewNoteNotesNoteIdGetResponses, ViewNoteNotesNoteIdGetErrors, ThrowOnError> => (options.client ?? client).get<ViewNoteNotesNoteIdGetResponses, ViewNoteNotesNoteIdGetErrors, ThrowOnError>({ url: '/notes/{note_id}', ...options });

/**
 * Edit Note
 */
export const editNoteNotesNoteIdPut = <ThrowOnError extends boolean = false>(options: Options<EditNoteNotesNoteIdPutData, ThrowOnError>): RequestResult<EditNoteNotesNoteIdPutResponses, EditNoteNotesNoteIdPutErrors, ThrowOnError> => (options.client ?? client).put<EditNoteNotesNoteIdPutResponses, EditNoteNotesNoteIdPutErrors, ThrowOnError>({
    url: '/notes/{note_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
