// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Note
 */
export type Note = {
    /**
     * Header
     */
    header: string;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Tags
     */
    tags: Array<Tag>;
};

/**
 * NoteOnCreate
 */
export type NoteOnCreate = {
    /**
     * Header
     */
    header: string;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * Tag
 */
export type Tag = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetNotesNotesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notes';
};

export type GetNotesNotesGetResponses = {
    /**
     * Response Get Notes Notes Get
     *
     * Successful Response
     */
    200: Array<Note>;
};

export type GetNotesNotesGetResponse = GetNotesNotesGetResponses[keyof GetNotesNotesGetResponses];

export type AddNoteNotesPostData = {
    body: NoteOnCreate;
    path?: never;
    query?: never;
    url: '/notes';
};

export type AddNoteNotesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddNoteNotesPostError = AddNoteNotesPostErrors[keyof AddNoteNotesPostErrors];

export type AddNoteNotesPostResponses = {
    /**
     * Successful Response
     */
    201: Note;
};

export type AddNoteNotesPostResponse = AddNoteNotesPostResponses[keyof AddNoteNotesPostResponses];

export type DeleteNoteNotesNoteIdDeleteData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/notes/{note_id}';
};

export type DeleteNoteNotesNoteIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNoteNotesNoteIdDeleteError = DeleteNoteNotesNoteIdDeleteErrors[keyof DeleteNoteNotesNoteIdDeleteErrors];

export type DeleteNoteNotesNoteIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ViewNoteNotesNoteIdGetData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/notes/{note_id}';
};

export type ViewNoteNotesNoteIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ViewNoteNotesNoteIdGetError = ViewNoteNotesNoteIdGetErrors[keyof ViewNoteNotesNoteIdGetErrors];

export type ViewNoteNotesNoteIdGetResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type ViewNoteNotesNoteIdGetResponse = ViewNoteNotesNoteIdGetResponses[keyof ViewNoteNotesNoteIdGetResponses];

export type EditNoteNotesNoteIdPutData = {
    body: NoteOnCreate;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/notes/{note_id}';
};

export type EditNoteNotesNoteIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditNoteNotesNoteIdPutError = EditNoteNotesNoteIdPutErrors[keyof EditNoteNotesNoteIdPutErrors];

export type EditNoteNotesNoteIdPutResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type EditNoteNotesNoteIdPutResponse = EditNoteNotesNoteIdPutResponses[keyof EditNoteNotesNoteIdPutResponses];
